ImperaPlus.Web/Areas/Admin/Controllers/GamesController.cs
using System;
using System.Linq;
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using ImperaPlus.Application.Games;
using ImperaPlus.Domain.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ImperaPlus.Backend.Areas.Admin.Controllers
{
    public class GamesController : BaseAdminController
    {
        private IGameService gameService;

        public GamesController(IUnitOfWork unitOfWork, IGameService gameService)
            : base(unitOfWork)
        {
            this.gameService = gameService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult View(long gameId)
        {
            var game = gameService.Get(gameId);

            AddLookups();

            return View(game);
        }

        [HttpPost]
        public DataTablesJsonResult Data(IDataTablesRequest request)
        {
            var data = unitOfWork.Games.Query();

            if (request.Search != null && !string.IsNullOrWhiteSpace(request.Search.Value))
            {
                var searchId = long.Parse(request.Search.Value);
                data = data.Where(x => x.Id == searchId);
            }

            var dataPage = data
                .OrderBy(x => x.Id)
                .Skip(request.Start)
                .Take(request.Length)
                .Select(g => new
                {
                    g.Id,
                    Type = g.Type.ToString(),
                    g.Name,
                    State = g.State.ToString(),
                    PlayState = g.PlayState.ToString(),
                    g.MapTemplateName,
                    CreatedBy = g.CreatedBy.UserName,
                    CurrentPlayer = "" // g.CurrentPlayer != null ? g.CurrentPlayer.User.UserName : ""
                });

            var response = DataTablesResponse.Create(request, data.Count(), data.Count(), dataPage);

            return new DataTablesJsonResult(response, true);
        }
    }
}

ImperaPlus.Web/Areas/Admin/Controllers/StatsController.cs
using System;
using System.Linq;
using ImperaPlus.Application.News;
using ImperaPlus.Backend.Areas.Admin.Lib;
using ImperaPlus.Domain.Enums;
using ImperaPlus.Domain.Repositories;
using ImperaPlus.Domain.Utilities;
using ImperaPlus.DTO.News;
using Microsoft.AspNetCore.Mvc;

namespace ImperaPlus.Backend.Areas.Admin.Controllers
{
    public class StatsController : BaseAdminController
    {
        public StatsController(IUnitOfWork unitOfWork)
            : base(unitOfWork)
        {
        }

        public ActionResult Index()
        {
            ViewBag.Logins60 = unitOfWork.Users.Query().Count(x => x.LastLogin >= DateTime.UtcNow.AddMinutes(-60));
            ViewBag.Logins120 = unitOfWork.Users.Query().Count(x => x.LastLogin >= DateTime.UtcNow.AddMinutes(-120));
            ViewBag.Games120 = unitOfWork.Games.Query()
                .Count(x => x.LastTurnStartedAt >= DateTime.UtcNow.AddMinutes(-120));
            ViewBag.ActiveGames = unitOfWork.Games.Query().Count(x => x.State == GameState.Active);

            ViewBag.Signedup7d = unitOfWork.Users.Query().Where(x => x.CreatedAt >= DateTime.UtcNow.AddDays(-7))
                .GroupBy(x => x.CreatedAt.Date)
                .Select(x =>
                    new { Count = x.Count(), Confirmed = x.Sum(y => y.EmailConfirmed ? 1 : 0), Day = x.Key }
                        .ToExpando())
                .ToList();

            ViewBag.UnconfirmedUsers = unitOfWork.Users.Query().Count(x => !x.EmailConfirmed);

            return View();
        }
    }
}

ImperaPlus.Web/Areas/Admin/Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using ImperaPlus.Application.Users;
using ImperaPlus.Domain;
using ImperaPlus.Domain.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ImperaPlus.Backend.Areas.Admin.Controllers
{
    public class UsersController : BaseAdminController
    {
        private readonly IUserService userService;
        private readonly UserManager<User> userManager;

        public UsersController(IUnitOfWork unitOfWork, IUserService userService, UserManager<User> userManager)
            : base(unitOfWork)
        {
            this.userService = userService;
            this.userManager = userManager;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(string userId)
        {
            var user = unitOfWork.Users.FindById(userId);
            if (user != null)
            {
                userService.DeleteAccount(user);

                return Ok();
            }

            return NotFound();
        }

        [HttpPost]
        public ActionResult Confirm(string userId)
        {
            var user = unitOfWork.Users.FindById(userId);
            if (user != null)
            {
                userService.ConfirmEmail(user);

                return Ok();
            }

            return NotFound();
        }

        [HttpGet]
        public ActionResult GetRoles()
        {
            var availableRoles = unitOfWork.Roles.Query()
                .Select(r => new { r.Id, r.Name })
                .ToList();
            return Json(availableRoles);
        }

        [HttpPost]
        public async Task<ActionResult> AddRole(string userId, string roleName)
        {
            var user = unitOfWork.Users.FindById(userId);
            if (user == null)
            {
                return NotFound();
            }

            var identityResult = await userManager.AddToRoleAsync(user, roleName);
            if (identityResult.Succeeded)
            {
                return Ok();
            }

            return BadRequest(identityResult.Errors);
        }

        [HttpPost]
        public async Task<ActionResult> RemoveRole(string userId, string roleName)
        {
            var user = unitOfWork.Users.FindById(userId);
            if (user == null)
            {
                return NotFound();
            }

            var identityResult = await userManager.RemoveFromRoleAsync(user, roleName);
            if (identityResult.Succeeded)
            {
                return Ok();
            }

            return BadRequest(identityResult.Errors);
        }

        [HttpPost]
        public DataTablesJsonResult Data(IDataTablesRequest request)
        {
            var roleFilter = HttpContext.Request.Form["roleFilter"].ToString();
            var rolesLookup = unitOfWork.Roles.Query().ToList();
            var data = unitOfWork.Users.Query();

            if (request.Search != null && !string.IsNullOrWhiteSpace(request.Search.Value))
            {
                data = data.Where(x =>
                    x.UserName.Contains(request.Search.Value) || x.Email.Contains(request.Search.Value));
            }

            if (!string.IsNullOrWhiteSpace(roleFilter))
            {
                var targetRole = rolesLookup.FirstOrDefault(r => r.Name == roleFilter);
                if (targetRole != null)
                {
                    data = data.Where(x => x.Roles.Any(r => r.RoleId == targetRole.Id));
                }
            }

            var filteredTotal = data.Count();

            var pageItems = data
                .OrderBy(x => x.UserName)
                .Skip(request.Start)
                .Take(request.Length)
                .Select(u => new
                {
                    u.Id,
                    Name = u.UserName,
                    u.Email,
                    u.EmailConfirmed,
                    u.IsDeleted,
                    RoleIds = u.Roles.Select(r => r.RoleId).ToList()
                })
                .ToList();

            // Map role IDs to role names in memory using dictionary for O(1) lookups
            var rolesDict = rolesLookup.ToDictionary(r => r.Id, r => r.Name);
            var resultItems = pageItems.Select(u => new
            {
                u.Id,
                u.Name,
                u.Email,
                u.EmailConfirmed,
                u.IsDeleted,
                Roles = u.RoleIds
                    .Where(rid => rolesDict.ContainsKey(rid))
                    .Select(rid => rolesDict[rid])
                    .ToList()
            }).ToList();

            var response = DataTablesResponse.Create(request, filteredTotal, filteredTotal, resultItems);

            return new DataTablesJsonResult(response, true);
        }
    }
}

ImperaPlus.Web/Controllers/NewsController.cs
using ImperaPlus.Application.News;
using ImperaPlus.DTO;
using ImperaPlus.DTO.News;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ImperaPlus.Backend.Controllers
{
    [Route("news")]
    [Authorize]
    [ProducesResponseType(typeof(ErrorResponse), 400)]
    [ProducesResponseType(typeof(void), 200)]
    public class NewsController : Controller
    {
        private readonly INewsService newsService;

        public NewsController(INewsService newsService)
        {
            this.newsService = newsService;
        }

        /// <summary>
        /// Returns the last 10 news items for all languages
        /// </summary>
        /// <returns>List of news items</returns>
        [HttpGet("")]
        [ProducesResponseType(typeof(IEnumerable<NewsItem>), 200)]
        public IEnumerable<NewsItem> GetAll()
        {
            return newsService.GetNews();
        }
    }
}

ImperaPlus.Web/Areas/Admin/Views/Shared/Navigation.cshtml
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="@Url.Action("Index", "Stats")"><i class="fa fa-line-chart fa-fw"></i> Statistics</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "News")"><i class="fa fa-newspaper-o fa-fw"></i> News</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Users")"><i class="fa fa-users fa-fw"></i> Users</a>
            </li>
            <li>
                <a href=""><i class="fa fa-list-ol fa-fw"></i> Ladders<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("Create", "Ladders")">Create</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Ladders")">List</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href=""><i class="fa fa-trophy fa-fw"></i> Tournaments<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("Create", "Tournaments")">Create</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Tournaments")">List</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="@Url.Action("Index", "Games")"><i class="fa fa-globe fa-fw"></i> Games</a>
            </li>
            <li>
                <a href="/api/admin/Hangfire"><i class="fa fa-wrench fa-fw"></i> Jobs</a>
            </li>
        </ul>
    </div>
</div>

ImperaPlus.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>ImperaPlus Admin - @ViewBag.Title</title>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/r/bs/dt-1.10.9,r-1.0.7/datatables.min.css"/>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <link rel="stylesheet" href="~/admin/font-awesome.css" type="text/css"/>
    <link rel="stylesheet" href="~/admin/jquery.dataTables.css" type="text/css"/>
    <link rel="stylesheet" href="~/admin/metisMenu.css" type="text/css"/>
    <link rel="stylesheet" href="~/admin/morris.css" type="text/css"/>
    <link rel="stylesheet" href="~/admin/sb-admin-2.css" type="text/css"/>
    <link rel="stylesheet" href="~/admin/bootstrap-datetimepicker.min.css" type="text/css"/>

    <link href="~/admin/site.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">ImperaPlus Admin</a>
        </div>

        @Html.Partial("Navigation")
    </nav>

    <div id="page-wrapper">
        <div class="row">
            @RenderBody()
        </div>
    </div>
</div>

<script src="~/admin/scripts/jquery.js"></script>
<script src="~/admin/scripts/bootstrap.js"></script>
<script src="~/admin/scripts/morris.js"></script>
<script src="~/admin/scripts/metisMenu.js"></script>
<script src="~/admin/scripts/sb-admin-2.js"></script>
<script src="~/admin/scripts/moment.min.js"></script>
<script src="~/admin/scripts/bootstrap-datetimepicker.min.js"></script>

<!-- CDN -->
<script src="//tinymce.cachefly.net/4.2/tinymce.min.js"></script>
<script src="https://cdn.tiny.cloud/1/e533gr1zr3jsg62xk7xkfu8ztxmdfoax3x5sesm6cv921pfz/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script type="text/javascript" src="https://cdn.datatables.net/r/bs/dt-1.10.9,r-1.0.7/datatables.min.js"></script>

@RenderSection("scripts", false)

<script type="text/javascript">
        $(function () {
            $('.datepicker').datetimepicker();
        });
    </script>

@RenderSection("imports", false);
</body>
</html>