ImperaPlus.Web/Areas/Admin/Controllers/TournamentsController.cs
using System;
using System.Collections.Generic;
using ImperaPlus.Application.Tournaments;
using ImperaPlus.Backend.Areas.Admin.Helpers;
using ImperaPlus.Domain.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ImperaPlus.Backend.Areas.Admin.Controllers
{
    public class TournamentsController : BaseAdminController
    {
        private ITournamentService tournamentService;

        public TournamentsController(IUnitOfWork unitOfWork, ITournamentService tournamentService)
            : base(unitOfWork)
        {
            this.tournamentService = tournamentService;
        }

        // GET: Admin/Tournaments
        public ActionResult Index()
        {
            AddLookups();

            var tournaments = tournamentService.GetRecentFull();

            return View(tournaments);
        }

        public ActionResult Show(Guid tournamentId)
        {
            AddLookups();

            var tournament = this.tournamentService.Get(tournamentId, false, false);

            return View(tournament);
        }

        public ActionResult Create()
        {
            AddLookups();

            var tournament = new DTO.Tournaments.Tournament
            {
                StartOfRegistration = DateTime.UtcNow.AddDays(1),
                StartOfTournament = DateTime.UtcNow.AddDays(2),

                MapTemplates = new string[0],
                Options = new DTO.Games.GameOptions { NumberOfTeams = 2 }
            };
            GameOptionsHelper.SetDefaultGameOptions(tournament.Options);

            ViewBag.FixedOptions = new HashSet<string> { "NumberOfTeams" };

            return View(tournament);
        }

        [HttpPost]
        public ActionResult PostCreate(DTO.Tournaments.Tournament tournament)
        {
            tournamentService.Create(tournament);

            return Redirect("Index");
        }

        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            tournamentService.Delete(id);

            return Redirect("Index");
        }
    }
}

ImperaPlus.Web/Controllers/TournamentController.cs
using System;
using System.Collections.Generic;
using ImperaPlus.Application.Tournaments;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ImperaPlus.DTO;
using ImperaPlus.Domain.Repositories;
using AutoMapper;

namespace ImperaPlus.Backend.Controllers
{
    [Authorize]
    [Route("tournaments")]
    [ProducesResponseType(typeof(ErrorResponse), 400)]
    [ProducesResponseType(typeof(void), 200)]
    public class TournamentController : Controller
    {
        private ITournamentService tournamentService;
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;

        public TournamentController(ITournamentService tournamentService, IUnitOfWork unitOfWork, IMapper mapper)
        {
            this.tournamentService = tournamentService;
            this.unitOfWork = unitOfWork;
            this.mapper = mapper;
        }

        /// <summary>
        /// Returns tournaments
        /// </summary>
        /// <returns>List of tournaments</returns>
        [HttpGet("")]
        [ProducesResponseType(typeof(IEnumerable<DTO.Tournaments.TournamentSummary>), 200)]
        public IActionResult GetAll()
        {
            return Ok(
                mapper.Map<IEnumerable<DTO.Tournaments.TournamentSummary>>(
                    unitOfWork.Tournaments.Get()
                )
            );
        }

        /// <summary>
        /// Get tournament identified by Id
        /// </summary>
        /// <param name="tournamentId">Id of tournament</param>
        [HttpGet("{tournamentId:guid}")]
        [ProducesResponseType(typeof(DTO.Tournaments.Tournament), 200)]
        public IActionResult GetById(Guid tournamentId)
        {
            return Ok(
                mapper.Map<DTO.Tournaments.Tournament>(
                    unitOfWork.Tournaments.GetById(tournamentId, readOnly: true)
                )
            );
        }

        /// <summary>
        /// Join tournament
        /// </summary>
        /// <param name="tournamentId">Id of tournament</param>
        [HttpPost("{tournamentId:guid}")]
        [ProducesResponseType(typeof(DTO.Tournaments.TournamentTeam), 200)]
        public IActionResult PostJoin(Guid tournamentId, string password = null)
        {
            return Ok(tournamentService.Join(tournamentId, password));
        }

        /// <summary>
        /// Get teams for tournament
        /// </summary>
        /// <param name="tournamentId">Id of tournament</param>
        [HttpGet("{tournamentId:guid}/teams")]
        [ProducesResponseType(typeof(IEnumerable<DTO.Tournaments.TournamentTeam>), 200)]
        public IActionResult GetTeams(Guid tournamentId)
        {
            return Ok(tournamentService.GetTeams(tournamentId));
        }

        /// <summary>
        /// Get teams for tournament pairing
        /// </summary>
        /// <param name="pairingId">Id of tournament pairing</param>
        [HttpGet("pairings/{pairingId:guid}/")]
        [ProducesResponseType(typeof(IEnumerable<DTO.Games.GameSummary>), 200)]
        public IActionResult GetGamesForPairing(Guid pairingId)
        {
            return Ok(tournamentService.GetGamesForPairing(pairingId));
        }

        /// <summary>
        /// Create new team for a tournament
        /// </summary>
        /// <param name="tournamentId">Id of tournament</param>
        /// <param name="name">Name of team</param>
        /// /// <param name="password">Optional password for team</param>
        /// <returns>Summary of newly created team</returns>
        [HttpPost("{tournamentId:guid}/teams")]
        [ProducesResponseType(typeof(DTO.Tournaments.TournamentTeam), 200)]
        public IActionResult PostCreateTeam(Guid tournamentId, string name, string password = null, string tournamentPassword = null)
        {
            return Ok(tournamentService.CreateTeam(tournamentId, name, password, tournamentPassword));
        }

        /// <summary>
        /// Join existing team
        /// </summary>
        /// <param name="tournamentId">Id of tournament</param>
        /// <param name="teamId">Id of team</param>
        /// <param name="password">Optional password for team to join</param>
        [HttpPost("{tournamentId:guid}/teams/{teamId:guid}")]
        [ProducesResponseType(typeof(DTO.Tournaments.TournamentTeam), 200)]
        public IActionResult PostJoinTeam(Guid tournamentId, Guid teamId, string password = null, string tournamentPassword = null)
        {
            return Ok(tournamentService.JoinTeam(tournamentId, teamId, password, tournamentPassword));
        }

        /// <summary>
        /// Delete a team. Only allowed if user created it
        /// </summary>
        /// <param name="tournamentId">Id of tournament</param>
        /// <param name="teamId">Id of team to delete</param>
        [HttpDelete("{tournamentId:guid}/teams/{teamId:guid}")]
        public IActionResult DeleteTeam(Guid tournamentId, Guid teamId)
        {
            tournamentService.DeleteTeam(tournamentId, teamId);

            return Ok();
        }

        /// <summary>
        /// Leave a team and tournament
        /// </summary>
        /// <param name="tournamentId">Id of tournament</param>
        [HttpDelete("{tournamentId:guid}/teams/me")]
        public IActionResult LeaveTournament(Guid tournamentId)
        {
            tournamentService.Leave(tournamentId);

            return Ok();
        }
    }
}

ImperaPlus.Web/Areas/Admin/Views/Tournaments/Create.cshtml
@model ImperaPlus.DTO.Tournaments.Tournament
@{
    ViewBag.Title = "Tournaments - Create";
}

<h2>New Tournament</h2>

@using (Html.BeginForm("PostCreate", "Tournaments", FormMethod.Post))
{
    <div class="panel panel-default">
        <div class="panel-heading" role="tab">
            <h4 class="panel-title"></h4>
        </div>
        <div class="panel-collapse">
            <div class="panel-body form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(x => x.Name, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(x => x.Name, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.Password, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.PasswordFor(x => x.Password, new { @class = "form-control", placeholder = "Leave empty for no password" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(x => x.StartOfRegistration, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(x => x.StartOfRegistration, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.StartOfTournament, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(x => x.StartOfTournament, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.NumberOfTeams, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(x => x.NumberOfTeams, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.NumberOfGroupGames, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(x => x.NumberOfGroupGames, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.NumberOfKnockoutGames, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(x => x.NumberOfKnockoutGames, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.NumberOfFinalGames, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(x => x.NumberOfFinalGames, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.MapTemplates, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.ListBoxFor(x => x.MapTemplates,
                            new MultiSelectList(ViewBag.MapTemplates as IEnumerable<string>, Model.MapTemplates),
                            new { @class = "form-control" })
                    </div>
                </div>

                @Html.EditorFor(x => x.Options, "../Shared/GameOptions", new { })
            </div>

            <div class="panel-footer clearfix">
                <div class="pull-right">
                    <button type="submit" class="btn btn-sm btn-info">Create</button>
                </div>
            </div>
        </div>
    </div>
}

ImperaPlus.Web/Areas/Admin/Views/Tournaments/Index.cshtml
@model IEnumerable<ImperaPlus.DTO.Tournaments.Tournament>
@{
    ViewBag.Title = "Tournaments";
}

<h2>Tournaments</h2>


@foreach (var tournament in Model)
{
    <div class="panel panel-default">
        <div class="panel-heading clearfix" role="tab">
            <h4 class="panel-title pull-left">
                <a class="collapsed" role="button" data-toggle="collapse" href="#tournament-@tournament.Id">
                    @tournament.Name - @tournament.Id
                </a>
            </h4>

            <div class="pull-right text-nowrap">
                <a class="btn btn-sm btn-default" href="@Url.Action("Show", "Tournaments", new { tournamentId = tournament.Id })">Details</a>
            </div>
        </div>

        @using (Html.BeginForm("PostUpdate", "Tournaments", FormMethod.Post))
        {
            @Html.HiddenFor(x => tournament.Id)

            <div class="panel-collapse collapse" id="tournament-@tournament.Id">
                <div class="panel-body form-horizontal">
                    <div class="form-group">
                        @Html.LabelFor(x => tournament.MapTemplates, new { @class = "control-label col-md-3" })
                        <div class="col-md-6">
                            @Html.ListBoxFor(x => tournament.MapTemplates,
                                new MultiSelectList(ViewBag.MapTemplates as IEnumerable<string>, tournament.MapTemplates),
                                new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => tournament.State, new { @class = "control-label col-md-3" })
                        <div class="col-md-6">
                            <div class="form-control-static">
                                @Html.DisplayTextFor(x => tournament.State)
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => tournament.Phase, new { @class = "control-label col-md-3" })
                        <div class="col-md-6">
                            <div class="form-control-static">
                                @Html.DisplayTextFor(x => tournament.Phase)
                            </div>
                        </div>
                    </div>

                    @Html.EditorFor(x => tournament.Options, "../Shared/GameOptions")
                </div>

                <div class="panel-footer clearfix">
                    <div class="pull-right">
                        <button type="submit" class="btn btn-sm btn-info">Update</button>
                    </div>
                </div>
            </div>
        }
    </div>
}

ImperaPlus.Web/Areas/Admin/Views/Tournaments/Show.cshtml
@model ImperaPlus.DTO.Tournaments.Tournament
@{
    ViewBag.Title = "Tournament";

    var tournament = Model;
}

<h2>Tournament - @tournament.Name - @tournament.Id</h2>

<div class="panel panel-default">
    <div class="panel-heading clearfix" role="tab">
        <h4 class="panel-title pull-left">
            <a class="collapsed" role="button" data-toggle="collapse" href="#tournament-@tournament.Id">
                Details
            </a>
        </h4>

        <div class="pull-right">
            @using (Html.BeginForm("Delete", "Tournaments", FormMethod.Post))
            {
                @Html.Hidden("id", tournament.Id)
                ;
                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
            }
        </div>
    </div>

    @using (Html.BeginForm("PostUpdate", "Tournaments", FormMethod.Post))
    {
        @Html.HiddenFor(x => tournament.Id)

        <div class="panel-collapse collapse" id="tournament-@tournament.Id">
            <div class="panel-body form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(x => tournament.MapTemplates, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.ListBoxFor(x => tournament.MapTemplates,
                            new MultiSelectList(ViewBag.MapTemplates as IEnumerable<string>, tournament.MapTemplates),
                            new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => tournament.State, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        <div class="form-control-static">
                            @Html.DisplayTextFor(x => tournament.State)
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => tournament.Phase, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        <div class="form-control-static">
                            @Html.DisplayTextFor(x => tournament.Phase)
                        </div>
                    </div>
                </div>

                @Html.EditorFor(x => tournament.Options, "../Shared/GameOptions")
            </div>

            <div class="panel-footer clearfix">
                <div class="pull-right">
                    <button type="submit" class="btn btn-sm btn-info">Update</button>
                </div>
            </div>
        </div>
    }
</div>

<div class="panel panel-default">
    <div class="panel-heading clearfix" role="tab">
        <h4 class="panel-title pull-left">
            <a class="collapsed" role="button" data-toggle="collapse" href="#tournament-players">
                Teams/Players
            </a>
        </h4>
    </div>

    <div class="panel-collapse collapse" id="tournament-players">
        <div class="panel-body form-horizontal">
            <ul>
            @foreach (var team in tournament.Teams)
            {
                <li>
                    @team.Id - @team.Name - @team.State
                    <ul>
                    @foreach (var participant in team.Participants)
                    {
                        <li>@participant.Id - @participant.Name</li>
                    }
                    </ul>
                </li>
            }
            </ul>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading clearfix" role="tab">
        <h4 class="panel-title pull-left">
            <a class="collapsed" role="button" data-toggle="collapse" href="#tournament-groups">
                Groups
            </a>
        </h4>
    </div>

    <div class="panel-collapse collapse" id="tournament-groups">
        <div class="panel-body form-horizontal">
            <ul>
            @foreach (var group in tournament.Groups)
            {
                <li>@group.Id</li>
            }
            </ul>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading clearfix" role="tab">
        <h4 class="panel-title pull-left">
            <a class="collapsed" role="button" data-toggle="collapse" href="#tournament-pairings">
                Pairings
            </a>
        </h4>
    </div>

    <div class="panel-collapse collapse" id="tournament-pairings">
        <div class="panel-body form-horizontal">
            <ul>
            @foreach (var pairing in tournament.Pairings)
            {
                <li>
                    @pairing.Id
                    <h5>Team A</h5>
                    <div>@pairing.TeamAWon</div>
                    <h5>Team B</h5>
                    <div>@pairing.TeamBWon</div>
                </li>
            }
            </ul>
        </div>

        <div class="panel-footer clearfix">
            <div class="pull-right">
                <button type="submit" class="btn btn-sm btn-info">Update</button>
            </div>
        </div>
    </div>
</div>