ImperaPlus.Web/Areas/Admin/Controllers/LaddersController.cs
using System;
using ImperaPlus.Application.Ladder;
using ImperaPlus.Domain.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ImperaPlus.Backend.Areas.Admin.Controllers
{
    public class LaddersController : BaseAdminController
    {
        private ILadderService ladderService;

        public LaddersController(IUnitOfWork unitOfWork, ILadderService ladderService)
            : base(unitOfWork)
        {
            this.ladderService = ladderService;
        }

        public ActionResult Index()
        {
            var ladders = ladderService.GetAllFull();

            AddLookups();

            return View(ladders);
        }

        public ActionResult Create()
        {
            AddLookups();

            var ladder = new DTO.Ladder.Ladder();
            ladder.Options = new DTO.Games.GameOptions();
            ladder.MapTemplates = new string[0];

            return View(ladder);
        }

        [HttpPost]
        public ActionResult PostUpdate(DTO.Ladder.Ladder ladder)
        {
            ladderService.UpdateName(ladder.Id, ladder.Name);
            ladderService.ToggleActive(ladder.Id, ladder.IsActive);
            ladderService.UpdateGameOptions(ladder.Id, ladder.Options);
            ladderService.UpdateMapTemplates(ladder.Id, ladder.MapTemplates);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult PostCreate(DTO.Ladder.Ladder ladder)
        {
            var summary = ladderService.Create(new DTO.Ladder.Admin.CreationOptions
            {
                Name = ladder.Name,
                NumberOfPlayers = ladder.Options.NumberOfPlayersPerTeam,
                NumberOfTeams = ladder.Options.NumberOfTeams
            });

            ladderService.UpdateGameOptions(summary.Id, ladder.Options);
            ladderService.UpdateMapTemplates(summary.Id, ladder.MapTemplates);
            ladderService.ToggleActive(summary.Id, ladder.IsActive);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult PostDelete(Guid id)
        {
            ladderService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

ImperaPlus.Web/Controllers/LadderController.cs
using System;
using System.Collections.Generic;
using ImperaPlus.Application.Ladder;
using ImperaPlus.DTO.Ladder;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ImperaPlus.DTO;

namespace ImperaPlus.Backend.Controllers
{
    /// <summary>
    /// Ladder interaction
    /// </summary>
    [Authorize]
    [Route("ladder")]
    [ProducesResponseType(typeof(ErrorResponse), 400)]
    [ProducesResponseType(typeof(void), 200)]
    public class LadderController : Controller
    {
        private ILadderService ladderService;

        public LadderController(ILadderService ladderService)
        {
            this.ladderService = ladderService;
        }

        /// <summary>
        /// Returns active ladders
        /// </summary>
        /// <returns>List of ladders</returns>
        [HttpGet("")]
        [ProducesResponseType(typeof(IEnumerable<LadderSummary>), 200)]
        public IEnumerable<LadderSummary> Get()
        {
            return ladderService.GetAll();
        }

        /// <summary>
        /// Gets ladder identified by given id
        /// </summary>
        /// <param name="ladderId">Id of ladder</param>        
        [HttpGet("{ladderId:guid}")]
        [ProducesResponseType(typeof(Ladder), 200)]
        public IActionResult Get(Guid ladderId)
        {
            return Ok(ladderService.Get(ladderId));
        }

        /// <summary>
        /// Queue up for a new game in the given ladder
        /// </summary>
        /// <param name="ladderId">Ladder id</param>
        [HttpPost("{ladderId:guid}/queue")]
        public IActionResult PostJoin(Guid ladderId)
        {
            ladderService.Queue(ladderId);

            return Ok();
        }

        /// <summary>
        /// Leave the queue for a ladder
        /// </summary>
        /// <param name="ladderId">Ladder Id</param>
        [HttpDelete("{ladderId:guid}/queue")]
        public IActionResult DeleteJoin(Guid ladderId)
        {
            ladderService.LeaveQueue(ladderId);

            return Ok();
        }
    }
}

ImperaPlus.Web/Areas/Admin/Views/Ladders/Create.cshtml
@model ImperaPlus.DTO.Ladder.Ladder
@{
    ViewBag.Title = "Ladders - Create";
}

<h2>New Ladder</h2>

@using (Html.BeginForm("PostCreate", "Ladders", FormMethod.Post))
{
    <div class="panel panel-default">
        <div class="panel-heading" role="tab">
            <h4 class="panel-title">

            </h4>
        </div>
        <div class="panel-collapse">
            <div class="panel-body form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(x => x.Name, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(x => x.Name)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-push-3 col-md-6 text-left">
                        <label>
                            @Html.EditorFor(x => x.IsActive) Is Active
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.MapTemplates, new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.ListBoxFor(x => x.MapTemplates,
                            new MultiSelectList(ViewBag.MapTemplates as IEnumerable<string>, Model.MapTemplates),
                            new { @class = "form-control" })
                    </div>
                </div>

                @Html.EditorFor(x => x.Options, "../Shared/GameOptions")
            </div>

            <div class="panel-footer clearfix">
                <div class="pull-right">
                    <button type="submit" class="btn btn-sm btn-info">Create</button>
                </div>
            </div>
        </div>
    </div>
}

ImperaPlus.Web/Areas/Admin/Views/Ladders/Index.cshtml
@model IEnumerable<ImperaPlus.DTO.Ladder.Ladder>
@{
    ViewBag.Title = "Ladders";
}

<h2>Ladders</h2>

@foreach (var ladder in Model)
{
    <div class="panel panel-default">
        <div class="panel-heading" role="tab">
            <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" href="#ladder-@ladder.Id">
                    @ladder.Name
                </a>
            </h4>
        </div>
        <div class="panel-collapse collapse" id="ladder-@ladder.Id">
            @using (Html.BeginForm("PostUpdate", "Ladders", FormMethod.Post))
            {
                @Html.HiddenFor(x => ladder.Id)
                <div class="panel-body form-horizontal">
                    <div class="form-group">
                        <div class="col-md-push-3 col-md-6 text-left">
                            <label>
                                @Html.LabelFor(x => ladder.Name, new { @class = "control-label col-md-3" })
                                @Html.EditorFor(model => ladder.Name)
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-push-3 col-md-6 text-left">
                            <label>
                                @Html.EditorFor(model => ladder.IsActive) Is Active
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => ladder.MapTemplates, new { @class = "control-label col-md-3" })
                        <div class="col-md-6">
                            @Html.ListBoxFor(x => ladder.MapTemplates,
                                new MultiSelectList(ViewBag.MapTemplates as IEnumerable<string>, ladder.MapTemplates),
                                new { @class = "form-control" })
                        </div>
                    </div>

                    @Html.EditorFor(x => ladder.Options, "../Shared/GameOptions")

                    <div class="pull-right">
                        <button type="submit" class="btn btn-sm btn-info">Update</button>
                    </div>
                </div>
            }

            <div class="panel-footer clearfix">
                <div class="pull-right">
                    @using (Html.BeginForm("PostDelete", "Ladders", FormMethod.Post))
                    {
                        @Html.Hidden("id", ladder.Id)
                        ;
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    }
                </div>
            </div>
        </div>
    </div>
}